connectionLimit: 10
host: localhost
port: 3306
user: admin
password: yamanash1
database: tournamentDB
socketPath: /var/run/mysqld/mysqld.sock

cookieSecret: zxcvbnm
cookieMaxage: 30
cookieSecure: false
